// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataAccessLayer is an autogenerated mock type for the DataAccessLayer type
type DataAccessLayer struct {
	mock.Mock
}

// Find provides a mock function with given fields: filter
func (_m *DataAccessLayer) Find(filter interface{}) ([]map[string]interface{}, error) {
	ret := _m.Called(filter)

	var r0 []map[string]interface{}
	if rf, ok := ret.Get(0).(func(interface{}) []map[string]interface{}); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
